import { defineField, defineType } from 'sanity'
import VideoInput from '../components/VideoInput'

export default defineType({
  name: 'heroSlide',
  title: 'Hero Slide',
  type: 'document',
  description:
    'Big rotating banners at the top of the landing page. Upload your own photo and write the headline + subtitle that appears over it.',
  fields: [
    defineField({
      name: 'backgroundType',
      title: 'Background',
      type: 'string',
      description: 'Choose whether this slide shows a photo or a video.',
      options: {
        list: [
          { title: 'Image', value: 'image' },
          { title: 'Video', value: 'video' },
        ],
        layout: 'radio',
      },
      initialValue: 'image',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'image',
      title: 'Background image',
      type: 'image',
      description: 'Wide, high-resolution photo (1920×1080 or larger). Also used as the video poster.',
      options: { hotspot: true },
      hidden: ({ parent }) => parent?.backgroundType === 'video' && Boolean(parent?.video),
      validation: (rule) =>
        rule.custom((value, context) =>
          context.parent?.backgroundType === 'video' || value ? true : 'Add a background image.',
        ),
    }),
    defineField({
      name: 'video',
      title: 'Background video',
      type: 'file',
      description: 'Short MP4/WebM clip. Plays muted on loop. Keep it small — it autoplays on mobile data too.',
      options: { accept: 'video/*' },
      components: { input: VideoInput },
      hidden: ({ parent }) => parent?.backgroundType !== 'video',
      validation: (rule) =>
        rule.custom((value, context) =>
          context.parent?.backgroundType !== 'video' || value ? true : 'Upload a background video.',
        ),
    }),
    defineField({
      name: 'headlineColor',
      title: 'Headline colour',
      type: 'string',
      description: 'Colour of the headline text. Use "Custom" below to enter any other colour.',
      options: {
        list: [
          { title: 'White', value: '#ffffff' },
          { title: 'Black', value: '#1a1a1a' },
          { title: 'Cream', value: '#fdf4ed' },
          { title: 'Beige', value: '#e8dacf' },
          { title: 'Light brown', value: '#bd8556' },
          { title: 'Brown', value: '#8b543d' },
          { title: 'Dark brown', value: '#642f00' },
          { title: 'Gold', value: '#d4a24c' },
          { title: 'Charcoal', value: '#2c2d2e' },
          { title: 'Sage', value: '#9caf88' },
          { title: 'Blush', value: '#f3a39b' },
          { title: 'Deep red', value: '#a3282a' },
          { title: 'Navy', value: '#1f3a5f' },
          { title: 'Teal', value: '#2f7d78' },
        ],
      },
      initialValue: '#ffffff',
    }),
    defineField({
      name: 'customHeadlineColor',
      title: 'Custom headline colour (hex)',
      type: 'string',
      description: 'Optional. Overrides the choice above, e.g. #ff6600.',
      validation: (rule) =>
        rule.regex(/^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$/, { name: 'hex colour' }).error('Use a hex value like #ff6600.'),
    }),
    defineField({
      name: 'subtitleColor',
      title: 'Subtitle colour',
      type: 'string',
      description: 'Colour of the subtitle text. Use "Custom" below to enter any other colour.',
      options: {
        list: [
          { title: 'White', value: '#ffffff' },
          { title: 'Black', value: '#1a1a1a' },
          { title: 'Cream', value: '#fdf4ed' },
          { title: 'Beige', value: '#e8dacf' },
          { title: 'Light brown', value: '#bd8556' },
          { title: 'Brown', value: '#8b543d' },
          { title: 'Dark brown', value: '#642f00' },
          { title: 'Gold', value: '#d4a24c' },
          { title: 'Charcoal', value: '#2c2d2e' },
          { title: 'Sage', value: '#9caf88' },
          { title: 'Blush', value: '#f3a39b' },
          { title: 'Deep red', value: '#a3282a' },
          { title: 'Navy', value: '#1f3a5f' },
          { title: 'Teal', value: '#2f7d78' },
        ],
      },
      initialValue: '#ffffff',
    }),
    defineField({
      name: 'customSubtitleColor',
      title: 'Custom subtitle colour (hex)',
      type: 'string',
      description: 'Optional. Overrides the choice above, e.g. #ff6600.',
      validation: (rule) =>
        rule.regex(/^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$/, { name: 'hex colour' }).error('Use a hex value like #ff6600.'),
    }),
    defineField({
      name: 'textColor',
      title: 'Text colour (legacy)',
      type: 'string',
      description: 'Old shared colour field, kept only for slides created before separate headline/subtitle colours existed.',
      hidden: true,
    }),
    defineField({
      name: 'customTextColor',
      title: 'Custom text colour (legacy)',
      type: 'string',
      hidden: true,
    }),
    defineField({
      name: 'fontFamily',
      title: 'Font',
      type: 'string',
      description: 'Font used for the headline and subtitle.',
      options: {
        list: [
          { title: 'Default (site heading)', value: 'default' },
          { title: 'Quicksand — rounded', value: "'Quicksand', sans-serif" },
          { title: 'Plus Jakarta Sans — modern', value: "'Plus Jakarta Sans', sans-serif" },
          { title: 'Be Vietnam Pro — clean', value: "'Be Vietnam Pro', sans-serif" },
          { title: 'Playfair Display — elegant serif', value: "'Playfair Display', serif" },
          { title: 'Bebas Neue — bold condensed', value: "'Bebas Neue', sans-serif" },
          { title: 'Georgia — classic serif', value: 'Georgia, serif' },
        ],
      },
      initialValue: 'default',
    }),
    defineField({
      name: 'headlineSize',
      title: 'Headline size',
      type: 'string',
      options: {
        list: [
          { title: 'Small', value: 'small' },
          { title: 'Medium', value: 'medium' },
          { title: 'Large', value: 'large' },
          { title: 'Extra large', value: 'xlarge' },
        ],
        layout: 'radio',
      },
      initialValue: 'medium',
    }),
    defineField({
      name: 'subtitleSize',
      title: 'Subtitle size',
      type: 'string',
      options: {
        list: [
          { title: 'Small', value: 'small' },
          { title: 'Medium', value: 'medium' },
          { title: 'Large', value: 'large' },
          { title: 'Extra large', value: 'xlarge' },
        ],
        layout: 'radio',
      },
      initialValue: 'medium',
    }),
    defineField({
      name: 'textAlign',
      title: 'Text box position (legacy)',
      type: 'string',
      hidden: true,
    }),
    defineField({
      name: 'headlinePosition',
      title: 'Headline position',
      type: 'string',
      description: 'Where the headline sits on the slide, independent of the subtitle.',
      options: {
        list: [
          { title: 'Top left', value: 'top-left' },
          { title: 'Top centre', value: 'top-center' },
          { title: 'Top right', value: 'top-right' },
          { title: 'Middle left', value: 'middle-left' },
          { title: 'Middle centre', value: 'middle-center' },
          { title: 'Middle right', value: 'middle-right' },
          { title: 'Bottom left', value: 'bottom-left' },
          { title: 'Bottom centre', value: 'bottom-center' },
          { title: 'Bottom right', value: 'bottom-right' },
        ],
      },
      initialValue: 'middle-center',
    }),
    defineField({
      name: 'headlineAlign',
      title: 'Headline text alignment',
      type: 'string',
      description: 'How the headline text itself is aligned within its own position.',
      options: {
        list: [
          { title: 'Left', value: 'left' },
          { title: 'Centre', value: 'center' },
          { title: 'Right', value: 'right' },
        ],
        layout: 'radio',
      },
      initialValue: 'center',
    }),
    defineField({
      name: 'subtitlePosition',
      title: 'Subtitle position',
      type: 'string',
      description: 'Where the subtitle sits on the slide, independent of the headline.',
      options: {
        list: [
          { title: 'Top left', value: 'top-left' },
          { title: 'Top centre', value: 'top-center' },
          { title: 'Top right', value: 'top-right' },
          { title: 'Middle left', value: 'middle-left' },
          { title: 'Middle centre', value: 'middle-center' },
          { title: 'Middle right', value: 'middle-right' },
          { title: 'Bottom left', value: 'bottom-left' },
          { title: 'Bottom centre', value: 'bottom-center' },
          { title: 'Bottom right', value: 'bottom-right' },
        ],
      },
      initialValue: 'middle-center',
    }),
    defineField({
      name: 'subtitleAlign',
      title: 'Subtitle text alignment',
      type: 'string',
      description: 'How the subtitle text itself is aligned within its own position.',
      options: {
        list: [
          { title: 'Left', value: 'left' },
          { title: 'Centre', value: 'center' },
          { title: 'Right', value: 'right' },
        ],
        layout: 'radio',
      },
      initialValue: 'center',
    }),
    defineField({
      name: 'textShadow',
      title: 'Text shadow',
      type: 'boolean',
      description: 'Adds a soft shadow so text stays readable over busy photos.',
      initialValue: true,
    }),
    defineField({
      name: 'overlayOpacity',
      title: 'Background dimming (%)',
      type: 'number',
      description: 'How much to darken the photo/video behind the text. 0 = none, 70 = very dark.',
      initialValue: 30,
      validation: (rule) => rule.min(0).max(90),
    }),
    defineField({
      name: 'title',
      title: 'Headline',
      type: 'string',
      description: 'Large text in the middle of the slide, e.g. "Crafted with Precision".',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'subtitle',
      title: 'Subtitle',
      type: 'string',
      description: 'Small uppercase text above the headline, e.g. "Anime Figures & Collectibles".',
    }),
    defineField({
      name: 'ctaLabel',
      title: 'Button text',
      type: 'string',
      description: 'Text on the button. Defaults to "Shop Now" if left empty.',
    }),
    defineField({
      name: 'ctaLink',
      title: 'Button link',
      type: 'string',
      description:
        'Where the button scrolls/links to. Use an on-page anchor like "#best-sellers" or a full URL. Defaults to "#best-sellers".',
    }),
    defineField({
      name: 'order',
      title: 'Display order',
      type: 'number',
      description: 'Lower numbers appear first in the slideshow.',
      initialValue: 0,
    }),
    defineField({
      name: 'active',
      title: 'Visible on site',
      type: 'boolean',
      description: 'Turn off to hide this slide without deleting it.',
      initialValue: true,
    }),
  ],
  orderings: [
    {
      title: 'Display order',
      name: 'orderAsc',
      by: [{ field: 'order', direction: 'asc' }],
    },
  ],
  preview: {
    select: { title: 'title', subtitle: 'subtitle', media: 'image' },
  },
})
